
package com.directv.afe.billing.invoice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "GetCustomerLastInvoiceException", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0")
public class GetCustomerLastInvoiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GetCustomerLastInvoiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GetCustomerLastInvoiceException_Exception(String message, GetCustomerLastInvoiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public GetCustomerLastInvoiceException_Exception(String message, GetCustomerLastInvoiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.directv.afe.billing.invoice.GetCustomerLastInvoiceException
     */
    public GetCustomerLastInvoiceException getFaultInfo() {
        return faultInfo;
    }

}
