
package com.directv.afe.billing.invoice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "GetCustomerFinancialTransactionsByCriteriaException", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0")
public class GetCustomerFinancialTransactionsByCriteriaException_Exception
    extends Exception
{
	private static final long serialVersionUID = 1L;
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GetCustomerFinancialTransactionsByCriteriaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GetCustomerFinancialTransactionsByCriteriaException_Exception(String message, GetCustomerFinancialTransactionsByCriteriaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public GetCustomerFinancialTransactionsByCriteriaException_Exception(String message, GetCustomerFinancialTransactionsByCriteriaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.directv.afe.billing.invoice.GetCustomerFinancialTransactionsByCriteriaException
     */
    public GetCustomerFinancialTransactionsByCriteriaException getFaultInfo() {
        return faultInfo;
    }

}
