
package com.directv.afe.billing.invoice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "GetLedgerAccountByIdException", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0")
public class GetLedgerAccountByIdException_Exception
    extends Exception
{
	private static final long serialVersionUID = 1L;
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GetLedgerAccountByIdException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GetLedgerAccountByIdException_Exception(String message, GetLedgerAccountByIdException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public GetLedgerAccountByIdException_Exception(String message, GetLedgerAccountByIdException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.directv.afe.billing.invoice.GetLedgerAccountByIdException
     */
    public GetLedgerAccountByIdException getFaultInfo() {
        return faultInfo;
    }

}
