
package com.directv.afe.billing.invoice;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ManageBillingEvents_pt", targetNamespace = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManageBillingEventsPt {


    /**
     * 
     * @param parameter
     * @return
     *     returns javax.xml.ws.Response<com.directv.afe.billing.invoice.GetCustomerFinancialAnalysisResponse>
     */
    @WebMethod(operationName = "GetCustomerFinancialAnalysis", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerFinancialAnalysis")
    public Response<GetCustomerFinancialAnalysisResponse> getCustomerFinancialAnalysisAsync(
        @WebParam(name = "GetCustomerFinancialAnalysisRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerFinancialAnalysisRequest parameter);

    /**
     * 
     * @param parameter
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetCustomerFinancialAnalysis", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerFinancialAnalysis")
    public Future<?> getCustomerFinancialAnalysisAsync(
        @WebParam(name = "GetCustomerFinancialAnalysisRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerFinancialAnalysisRequest parameter,
        @WebParam(name = "GetCustomerFinancialAnalysisResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCustomerFinancialAnalysisResponse> asyncHandler);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.directv.afe.billing.invoice.GetCustomerFinancialAnalysisResponse
     * @throws GetCustomerFinancialAnalysisException_Exception
     */
    @WebMethod(operationName = "GetCustomerFinancialAnalysis", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerFinancialAnalysis")
    @WebResult(name = "GetCustomerFinancialAnalysisResponse", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "paramter")
    public GetCustomerFinancialAnalysisResponse getCustomerFinancialAnalysis(
        @WebParam(name = "GetCustomerFinancialAnalysisRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerFinancialAnalysisRequest parameter)
        throws GetCustomerFinancialAnalysisException_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns javax.xml.ws.Response<com.directv.afe.billing.invoice.GetCustomerFinancialInfoResponse>
     */
    @WebMethod(operationName = "GetCustomerFinancialInfo", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerFinancialInfo")
    public Response<GetCustomerFinancialInfoResponse> getCustomerFinancialInfoAsync(
        @WebParam(name = "GetCustomerFinancialInfoRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerFinancialInfoRequest parameter);

    /**
     * 
     * @param parameter
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetCustomerFinancialInfo", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerFinancialInfo")
    public Future<?> getCustomerFinancialInfoAsync(
        @WebParam(name = "GetCustomerFinancialInfoRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerFinancialInfoRequest parameter,
        @WebParam(name = "GetCustomerFinancialInfoResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCustomerFinancialInfoResponse> asyncHandler);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.directv.afe.billing.invoice.GetCustomerFinancialInfoResponse
     * @throws GetCustomerFinancialInfoException_Exception
     */
    @WebMethod(operationName = "GetCustomerFinancialInfo", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerFinancialInfo")
    @WebResult(name = "GetCustomerFinancialInfoResponse", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
    public GetCustomerFinancialInfoResponse getCustomerFinancialInfo(
        @WebParam(name = "GetCustomerFinancialInfoRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerFinancialInfoRequest parameter)
        throws GetCustomerFinancialInfoException_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns javax.xml.ws.Response<com.directv.afe.billing.invoice.GetCustomerFinancialTransactionResponse>
     */
    @WebMethod(operationName = "GetCustomerFinancialTransaction", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerFinancialTransaction")
    public Response<GetCustomerFinancialTransactionResponse> getCustomerFinancialTransactionAsync(
        @WebParam(name = "GetCustomerFinancialTransactionRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerFinancialTransactionRequest parameter);

    /**
     * 
     * @param parameter
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetCustomerFinancialTransaction", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerFinancialTransaction")
    public Future<?> getCustomerFinancialTransactionAsync(
        @WebParam(name = "GetCustomerFinancialTransactionRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerFinancialTransactionRequest parameter,
        @WebParam(name = "GetCustomerFinancialTransactionResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCustomerFinancialTransactionResponse> asyncHandler);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.directv.afe.billing.invoice.GetCustomerFinancialTransactionResponse
     * @throws GetCustomerFinancialTransactionException_Exception
     */
    @WebMethod(operationName = "GetCustomerFinancialTransaction", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerFinancialTransaction")
    @WebResult(name = "GetCustomerFinancialTransactionResponse", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
    public GetCustomerFinancialTransactionResponse getCustomerFinancialTransaction(
        @WebParam(name = "GetCustomerFinancialTransactionRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerFinancialTransactionRequest parameter)
        throws GetCustomerFinancialTransactionException_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns javax.xml.ws.Response<com.directv.afe.billing.invoice.GetCustomerFinancialTransactionsResponse>
     */
    @WebMethod(operationName = "GetCustomerFinancialTransactions", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerFinancialTransactions")
    public Response<GetCustomerFinancialTransactionsResponse> getCustomerFinancialTransactionsAsync(
        @WebParam(name = "GetCustomerFinancialTransactionsRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerFinancialTransactionsRequest parameter);

    /**
     * 
     * @param parameter
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetCustomerFinancialTransactions", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerFinancialTransactions")
    public Future<?> getCustomerFinancialTransactionsAsync(
        @WebParam(name = "GetCustomerFinancialTransactionsRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerFinancialTransactionsRequest parameter,
        @WebParam(name = "GetCustomerFinancialTransactionsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCustomerFinancialTransactionsResponse> asyncHandler);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.directv.afe.billing.invoice.GetCustomerFinancialTransactionsResponse
     * @throws GetCustomerFinancialTransactionsException_Exception
     */
    @WebMethod(operationName = "GetCustomerFinancialTransactions", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerFinancialTransactions")
    @WebResult(name = "GetCustomerFinancialTransactionsResponse", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
    public GetCustomerFinancialTransactionsResponse getCustomerFinancialTransactions(
        @WebParam(name = "GetCustomerFinancialTransactionsRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerFinancialTransactionsRequest parameter)
        throws GetCustomerFinancialTransactionsException_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns javax.xml.ws.Response<com.directv.afe.billing.invoice.GetCustomerInvoiceByIdResponse>
     */
    @WebMethod(operationName = "GetCustomerInvoiceById", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerInvoiceById")
    public Response<GetCustomerInvoiceByIdResponse> getCustomerInvoiceByIdAsync(
        @WebParam(name = "GetCustomerInvoiceByIdRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerInvoiceByIdRequest parameter);

    /**
     * 
     * @param parameter
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetCustomerInvoiceById", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerInvoiceById")
    public Future<?> getCustomerInvoiceByIdAsync(
        @WebParam(name = "GetCustomerInvoiceByIdRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerInvoiceByIdRequest parameter,
        @WebParam(name = "GetCustomerInvoiceByIdResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCustomerInvoiceByIdResponse> asyncHandler);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.directv.afe.billing.invoice.GetCustomerInvoiceByIdResponse
     * @throws GetCustomerInvoiceByIdException_Exception
     */
    @WebMethod(operationName = "GetCustomerInvoiceById", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerInvoiceById")
    @WebResult(name = "GetCustomerInvoiceByIdResponse", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
    public GetCustomerInvoiceByIdResponse getCustomerInvoiceById(
        @WebParam(name = "GetCustomerInvoiceByIdRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerInvoiceByIdRequest parameter)
        throws GetCustomerInvoiceByIdException_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns javax.xml.ws.Response<com.directv.afe.billing.invoice.GetCustomerInvoicesResponse>
     */
    @WebMethod(operationName = "GetCustomerInvoices", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerInvoices")
    public Response<GetCustomerInvoicesResponse> getCustomerInvoicesAsync(
        @WebParam(name = "GetCustomerInvoicesRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerInvoicesRequest parameter);

    /**
     * 
     * @param parameter
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetCustomerInvoices", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerInvoices")
    public Future<?> getCustomerInvoicesAsync(
        @WebParam(name = "GetCustomerInvoicesRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerInvoicesRequest parameter,
        @WebParam(name = "GetCustomerInvoicesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCustomerInvoicesResponse> asyncHandler);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.directv.afe.billing.invoice.GetCustomerInvoicesResponse
     * @throws GetCustomerInvoicesException_Exception
     */
    @WebMethod(operationName = "GetCustomerInvoices", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerInvoices")
    @WebResult(name = "GetCustomerInvoicesResponse", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
    public GetCustomerInvoicesResponse getCustomerInvoices(
        @WebParam(name = "GetCustomerInvoicesRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerInvoicesRequest parameter)
        throws GetCustomerInvoicesException_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns javax.xml.ws.Response<com.directv.afe.billing.invoice.GetCustomerLastInvoiceResponse>
     */
    @WebMethod(operationName = "GetCustomerLastInvoice", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerLastInvoice")
    public Response<GetCustomerLastInvoiceResponse> getCustomerLastInvoiceAsync(
        @WebParam(name = "GetCustomerLastInvoiceRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerLastInvoiceRequest parameter);

    /**
     * 
     * @param parameter
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetCustomerLastInvoice", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerLastInvoice")
    public Future<?> getCustomerLastInvoiceAsync(
        @WebParam(name = "GetCustomerLastInvoiceRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerLastInvoiceRequest parameter,
        @WebParam(name = "GetCustomerLastInvoiceResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCustomerLastInvoiceResponse> asyncHandler);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.directv.afe.billing.invoice.GetCustomerLastInvoiceResponse
     * @throws GetCustomerLastInvoiceException_Exception
     */
    @WebMethod(operationName = "GetCustomerLastInvoice", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerLastInvoice")
    @WebResult(name = "GetCustomerLastInvoiceResponse", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
    public GetCustomerLastInvoiceResponse getCustomerLastInvoice(
        @WebParam(name = "GetCustomerLastInvoiceRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerLastInvoiceRequest parameter)
        throws GetCustomerLastInvoiceException_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns javax.xml.ws.Response<com.directv.afe.billing.invoice.GetLedgerAccountByIdResponse>
     */
    @WebMethod(operationName = "GetLedgerAccountById", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetLedgerAccountById")
    public Response<GetLedgerAccountByIdResponse> getLedgerAccountByIdAsync(
        @WebParam(name = "GetLedgerAccountByIdRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetLedgerAccountByIdRequest parameter);

    /**
     * 
     * @param parameter
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetLedgerAccountById", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetLedgerAccountById")
    public Future<?> getLedgerAccountByIdAsync(
        @WebParam(name = "GetLedgerAccountByIdRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetLedgerAccountByIdRequest parameter,
        @WebParam(name = "GetLedgerAccountByIdResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetLedgerAccountByIdResponse> asyncHandler);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.directv.afe.billing.invoice.GetLedgerAccountByIdResponse
     * @throws GetLedgerAccountByIdException_Exception
     */
    @WebMethod(operationName = "GetLedgerAccountById", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetLedgerAccountById")
    @WebResult(name = "GetLedgerAccountByIdResponse", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
    public GetLedgerAccountByIdResponse getLedgerAccountById(
        @WebParam(name = "GetLedgerAccountByIdRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetLedgerAccountByIdRequest parameter)
        throws GetLedgerAccountByIdException_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns javax.xml.ws.Response<com.directv.afe.billing.invoice.GetCustomerFinancialTransactionsByCriteriaResponse>
     */
    @WebMethod(operationName = "GetCustomerFinancialTransactionsByCriteria", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerFinancialTransactionsByCriteria")
    public Response<GetCustomerFinancialTransactionsByCriteriaResponse> getCustomerFinancialTransactionsByCriteriaAsync(
        @WebParam(name = "GetCustomerFinancialTransactionsByCriteriaRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerFinancialTransactionsByCriteriaRequest parameter);

    /**
     * 
     * @param parameter
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetCustomerFinancialTransactionsByCriteria", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerFinancialTransactionsByCriteria")
    public Future<?> getCustomerFinancialTransactionsByCriteriaAsync(
        @WebParam(name = "GetCustomerFinancialTransactionsByCriteriaRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerFinancialTransactionsByCriteriaRequest parameter,
        @WebParam(name = "GetCustomerFinancialTransactionsByCriteriaResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCustomerFinancialTransactionsByCriteriaResponse> asyncHandler);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.directv.afe.billing.invoice.GetCustomerFinancialTransactionsByCriteriaResponse
     * @throws GetCustomerFinancialTransactionsByCriteriaException_Exception
     */
    @WebMethod(operationName = "GetCustomerFinancialTransactionsByCriteria", action = "http://directvla.com/contract/businessdomain/ManageBillingEvents/v1-0/GetCustomerFinancialTransactionsByCriteria")
    @WebResult(name = "GetCustomerFinancialTransactionsByCriteriaResponse", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
    public GetCustomerFinancialTransactionsByCriteriaResponse getCustomerFinancialTransactionsByCriteria(
        @WebParam(name = "GetCustomerFinancialTransactionsByCriteriaRequest", targetNamespace = "http://directvla.com/schema/businessdomain/ManageBillingEvents/v1-0", partName = "parameter")
        GetCustomerFinancialTransactionsByCriteriaRequest parameter)
        throws GetCustomerFinancialTransactionsByCriteriaException_Exception
    ;

}
