#Application Name
spring:
 application:
  name: e-invoice
     

#Component Info 
info:
 component: eInvoiceAPI

#Port - If 0 get random port
server: 
 port: 0

#Eureka Instance ID
eureka:
 instance:
  instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  
ribbon:
  eureka:
    enabled: true
 
#Service Registration Method 
cloud:
 services:
  registrationMethod: route
 
#Disable HTTP Basic Authentication
security:
 basic:
  enabled: false