http:
  port: 8081

service:
  customer:
    url: http://localhost:9093/DTVLA-Services/CRMSupportAndReadinessService
  invoice:
    url: http://rgqamesb.dtvdev.net:80/DTVLA-Services/ManageBillingEventsService