http:
  port: 8081

service:
  customer:
    url: http://localhost:9093/DTVLA-Services/CRMSupportAndReadinessService
    reason: 1
  invoice:
    url: http://rgqamesb.dtvdev.net:80/DTVLA-Services/ManageBillingEventsService
    
queues:
  capacity:
    error: 10000
    cutomer: 10000
    mail: 10000
    invoice: 10000
    end: 10000
    