
package com.directvla.contract.businessdomain.crmsupportandreadiness.v1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CRMSupportAndReadiness_pt", targetNamespace = "http://directvla.com/contract/businessdomain/CRMSupportAndReadiness/v1-0", wsdlLocation = "file:/home/marco/Code/Java/dtv/poc/code/billingAPI/src/test/resources/CRMSupportAndReadinessService.wsdl")
public class CRMSupportAndReadinessPt_Service
    extends Service
{

    private final static URL CRMSUPPORTANDREADINESSPT_WSDL_LOCATION;
    private final static WebServiceException CRMSUPPORTANDREADINESSPT_EXCEPTION;
    private final static QName CRMSUPPORTANDREADINESSPT_QNAME = new QName("http://directvla.com/contract/businessdomain/CRMSupportAndReadiness/v1-0", "CRMSupportAndReadiness_pt");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/marco/Code/Java/dtv/poc/code/billingAPI/src/test/resources/CRMSupportAndReadinessService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CRMSUPPORTANDREADINESSPT_WSDL_LOCATION = url;
        CRMSUPPORTANDREADINESSPT_EXCEPTION = e;
    }

    public CRMSupportAndReadinessPt_Service() {
        super(__getWsdlLocation(), CRMSUPPORTANDREADINESSPT_QNAME);
    }

    public CRMSupportAndReadinessPt_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CRMSUPPORTANDREADINESSPT_QNAME, features);
    }

    public CRMSupportAndReadinessPt_Service(URL wsdlLocation) {
        super(wsdlLocation, CRMSUPPORTANDREADINESSPT_QNAME);
    }

    public CRMSupportAndReadinessPt_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CRMSUPPORTANDREADINESSPT_QNAME, features);
    }

    public CRMSupportAndReadinessPt_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CRMSupportAndReadinessPt_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CRMSupportAndReadinessPt
     */
    @WebEndpoint(name = "CRMSupportAndReadiness_ptPort")
    public CRMSupportAndReadinessPt getCRMSupportAndReadinessPtPort() {
        return super.getPort(new QName("http://directvla.com/contract/businessdomain/CRMSupportAndReadiness/v1-0", "CRMSupportAndReadiness_ptPort"), CRMSupportAndReadinessPt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRMSupportAndReadinessPt
     */
    @WebEndpoint(name = "CRMSupportAndReadiness_ptPort")
    public CRMSupportAndReadinessPt getCRMSupportAndReadinessPtPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://directvla.com/contract/businessdomain/CRMSupportAndReadiness/v1-0", "CRMSupportAndReadiness_ptPort"), CRMSupportAndReadinessPt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CRMSUPPORTANDREADINESSPT_EXCEPTION!= null) {
            throw CRMSUPPORTANDREADINESSPT_EXCEPTION;
        }
        return CRMSUPPORTANDREADINESSPT_WSDL_LOCATION;
    }

}
