
package com.directv.email.computec;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsDirectvIVRService", targetNamespace = "http://co.com.computec.directvivr.ws/", wsdlLocation = "file:/home/victormartinez/directv/afe/EBGW-72/inicio/code/emailAPI/src/test/resources/WsDirectvIVRService.wsdl")
public class WsDirectvIVRService
    extends Service
{

    private final static URL WSDIRECTVIVRSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSDIRECTVIVRSERVICE_EXCEPTION;
    private final static QName WSDIRECTVIVRSERVICE_QNAME = new QName("http://co.com.computec.directvivr.ws/", "WsDirectvIVRService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/victormartinez/directv/afe/EBGW-72/inicio/code/emailAPI/src/test/resources/WsDirectvIVRService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSDIRECTVIVRSERVICE_WSDL_LOCATION = url;
        WSDIRECTVIVRSERVICE_EXCEPTION = e;
    }

    public WsDirectvIVRService() {
        super(__getWsdlLocation(), WSDIRECTVIVRSERVICE_QNAME);
    }

    public WsDirectvIVRService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSDIRECTVIVRSERVICE_QNAME, features);
    }

    public WsDirectvIVRService(URL wsdlLocation) {
        super(wsdlLocation, WSDIRECTVIVRSERVICE_QNAME);
    }

    public WsDirectvIVRService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSDIRECTVIVRSERVICE_QNAME, features);
    }

    public WsDirectvIVRService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsDirectvIVRService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsDirectvIVR
     */
    @WebEndpoint(name = "WsDirectvIVRPort")
    public WsDirectvIVR getWsDirectvIVRPort() {
        return super.getPort(new QName("http://co.com.computec.directvivr.ws/", "WsDirectvIVRPort"), WsDirectvIVR.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsDirectvIVR
     */
    @WebEndpoint(name = "WsDirectvIVRPort")
    public WsDirectvIVR getWsDirectvIVRPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://co.com.computec.directvivr.ws/", "WsDirectvIVRPort"), WsDirectvIVR.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSDIRECTVIVRSERVICE_EXCEPTION!= null) {
            throw WSDIRECTVIVRSERVICE_EXCEPTION;
        }
        return WSDIRECTVIVRSERVICE_WSDL_LOCATION;
    }

}
