#Component Info
info:
 component: Zuul-Server
 
#Spring Application Name 
spring:
 application:
  name: Zuul-Server 
 
#Server Port
server:
 port: 8080 

#Endpoints 
endpoints:
 restart:
  enabled: true
 shutdown:
  enabled: true
 health:
  sensitive: false

#Zuul routes active 
zuul: 
 routes:
  users: 
   path: /einvoice/**
   serviceId: e-invoice
 
#Eureka Instance ID
eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_IP:localhost}:8761/eureka/ 

#Ribbon Activation
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true
  
#resolve the service time-out exception
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000 # Increase the Hystrix timeout to 60s (globally)



 