#Application Name
spring:
 application:
  name: email
     

#Component Info 
info:
 component: emailAPI

#Port - If 0 get random port
server: 
 port: 0

#Eureka Instance ID
eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_IP:localhost}:8761/eureka/ 

 
#Service Registration Method 
cloud:
 services:
  registrationMethod: route
 
#Disable HTTP Basic Authentication
security:
 basic:
  enabled: false