# HTTP Server
server: 
 port: 8761

# Eureka Configuration Properties
eureka:
 client:
  registerWithEureka: false
  fetchRegistry: false
  serviceUrl:
      defaultZone: http://172.18.0.3:8761/eureka
 server:
  waitTimeInMsWhenSyncEmpty: 0
  
  