
package com.directv.email.exacttarget;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * ExactTarget Partner API
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PartnerAPI", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", wsdlLocation = "file:/home/victormartinez/directv/afe/EBGW-72/inicio/code/emailAPI/src/test/resources/ExactTarget.wsdl")
public class PartnerAPI
    extends Service
{

    private final static URL PARTNERAPI_WSDL_LOCATION;
    private final static WebServiceException PARTNERAPI_EXCEPTION;
    private final static QName PARTNERAPI_QNAME = new QName("http://exacttarget.com/wsdl/partnerAPI", "PartnerAPI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/victormartinez/directv/afe/EBGW-72/inicio/code/emailAPI/src/test/resources/ExactTarget.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARTNERAPI_WSDL_LOCATION = url;
        PARTNERAPI_EXCEPTION = e;
    }

    public PartnerAPI() {
        super(__getWsdlLocation(), PARTNERAPI_QNAME);
    }

    public PartnerAPI(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARTNERAPI_QNAME, features);
    }

    public PartnerAPI(URL wsdlLocation) {
        super(wsdlLocation, PARTNERAPI_QNAME);
    }

    public PartnerAPI(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARTNERAPI_QNAME, features);
    }

    public PartnerAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PartnerAPI(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Soap
     */
    @WebEndpoint(name = "Soap")
    public Soap getSoap() {
        return super.getPort(new QName("http://exacttarget.com/wsdl/partnerAPI", "Soap"), Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Soap
     */
    @WebEndpoint(name = "Soap")
    public Soap getSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://exacttarget.com/wsdl/partnerAPI", "Soap"), Soap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARTNERAPI_EXCEPTION!= null) {
            throw PARTNERAPI_EXCEPTION;
        }
        return PARTNERAPI_WSDL_LOCATION;
    }

}
